filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'app/*'
        - 'bin/*'
        - 'library/*'
    paths: {  }
tools:
    php_sim:
        enabled: true
        min_mass: 16
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
    php_analyzer:
        config:
            check_calls:
                enabled: false
                method_call_validity: false
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
        path_configs: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
    external_code_coverage:
        timeout: 600
after_commands: {  }
artifacts: {  }
build_failure_conditions: {  }
