language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --dev --prefer-source

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar 
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script: phpunit --coverage-clover=coverage.clover
